### ISSUE TITLE
How does the algorithm work?

### ISSUE THREAD

**Issue by nok** [iarthstar/Image2Palette#3]
Nice work @iarthstar !

Can you describe how the algorithm of determining the colors works? After a short insepction I didn't find any relevant parts in the source code for that.

Thanks,
Darius

**Comment by iarthstar** [comment]
Actually, I'm not determining the colors myself, I'm using Imagga Colors API for that i.e. the below code

```purescript
launchAff_ do
              result <- sequential $
                Tuple <$> parallel (fetch configColors)
                      <*> parallel (fetch configUsage)
              case result of
                Tuple (Right (ColorsRes colorsRes)) (Right (UsageRes usageRes)) -> do
                    let colors = map (\c -> c ^. _html_code) (colorsRes.result ^. _colors ^. _image_colors)
```

But if you want to do that, please have a look at this repo : [get-rgba-palette](https://github.com/mattdesl/get-rgba-palette)
