### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by patriciasofialourenco** [iarthstar/Image2Palette#5]
Unable to use this plugin. I've downloaded it, install was successful but when I select "Get Palette", it says "Generating", followed by "Something went wrong".
I'm using Sketch 55.3 on macOS High Sierra

**Comment by iarthstar** [comment]
Did you copy pasted the Auth String correctly ?

Like extra spaces ?

**Comment by patriciasofialourenco** [comment]
Yes

**Comment by iarthstar** [comment]
I want to clarify, it only works with ImageLayer i.e. Bitmap
Not with ShapeLayer i.e. Rectangle or Oval with Image background.

I need some more info :

Please perform the following steps :
- Open MacOS Console App, type in 'sketch' in the search bar and press enter
- Change the 'ANY' to 'PROCESS' in the search bar
- Open Sketch App and try to generate the palette
- Some logs will show up, Just share those with me

**Comment by patriciasofialourenco** [comment]
default	11:29:20.444697 -0500	Sketch	TIC TCP Conn Cancel [34:0x60000037ea80]
default	11:29:20.445373 -0500	Sketch	[34 <private> stream, pid: 65172, url: https://gate.hockeyapp.net/v2/track, tls] cancelled
	[34.1 00EC1A91-88B5-44AD-81E1-887049E39F18 <private>.52142<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns
	Duration: 60.160s, DNS @0.000s took 0.021s, TCP @0.022s took 0.014s, TLS took 0.057s
	bytes in/out: 7442/1347, packets in/out: 7/4, rtt: 0.013s, retransmitted packets: 0, out-of-order packets: 0
default	11:29:33.767160 -0500	Sketch	UNIX error exception: 17
default	11:29:33.786020 -0500	Sketch	UNIX error exception: 17
default	11:29:35.681827 -0500	Sketch	No WebView present. Event cannot be posted to the web UI.
default	11:29:39.601130 -0500	Sketch	TIC Enabling TLS [35:0x60000037f740]
default	11:29:39.601200 -0500	Sketch	TIC TCP Conn Start [35:0x60000037f740]
default	11:29:39.601795 -0500	Sketch	Task <A10712AD-C71D-4342-86CB-37CB356D87D4>.<25> setting up Connection 35
default	11:29:39.601887 -0500	Sketch	[35 <private> <private>] start
default	11:29:39.720967 -0500	Sketch	TIC TLS Event [35:0x60000037f740]: 1, Pending(0)
default	11:29:39.781560 -0500	Sketch	TIC TLS Event [35:0x60000037f740]: 2, Pending(0)
default	11:29:39.784145 -0500	Sketch	TIC TLS Event [35:0x60000037f740]: 11, Pending(0)
default	11:29:39.785933 -0500	Sketch	TIC TLS Event [35:0x60000037f740]: 12, Pending(0)
default	11:29:39.785997 -0500	Sketch	TIC TLS Event [35:0x60000037f740]: 14, Pending(0)
default	11:29:39.819625 -0500	Sketch	System Trust Evaluation yielded status(0)
default	11:29:39.829946 -0500	Sketch	TIC TLS Trust Result [35:0x60000037f740]: 0
default	11:29:39.868132 -0500	Sketch	TIC TLS Event [35:0x60000037f740]: 20, Pending(0)
default	11:29:39.868199 -0500	Sketch	TIC TCP Conn Connected [35:0x60000037f740]: Err(16)
default	11:29:39.868873 -0500	Sketch	TIC TCP Conn Event [35:0x60000037f740]: 1
default	11:29:39.868955 -0500	Sketch	TIC TCP Conn Event [35:0x60000037f740]: 8
default	11:29:39.869104 -0500	Sketch	TIC TLS Handshake Complete [35:0x60000037f740]
default	11:29:39.870778 -0500	Sketch	Task <A10712AD-C71D-4342-86CB-37CB356D87D4>.<25> now using Connection 35
default	11:29:39.871230 -0500	Sketch	Task <85E2075F-9F70-47B1-9B98-A838268294A7>.<26> now using Connection 35
default	11:29:39.871447 -0500	Sketch	Task <85E2075F-9F70-47B1-9B98-A838268294A7>.<26> sent request, body N
default	11:29:40.124759 -0500	Sketch	Task <85E2075F-9F70-47B1-9B98-A838268294A7>.<26> received response, status 200 content K
default	11:29:40.124991 -0500	Sketch	Task <85E2075F-9F70-47B1-9B98-A838268294A7>.<26> response ended
default	11:29:40.143087 -0500	Sketch	SUCCESS -----> {"result":{"billing_period_end":"15 of Dec, 2019","billing_period_start":"15 of Nov, 2019","daily_for":"15 of Nov, 2019","daily_processed":24,"daily_requests":49,"last_usage":1573835324,"monthly_processed":24,"monthly_requests":49,"weekly_processed":24,"weekly_requests":49},"status":{"text":"","type":"success"}}
default	11:29:40.591808 -0500	Sketch	Task <A10712AD-C71D-4342-86CB-37CB356D87D4>.<25> sent request, body S
default	11:29:42.052944 -0500	Sketch	Task <A10712AD-C71D-4342-86CB-37CB356D87D4>.<25> received response, status 200 content K
default	11:29:42.053155 -0500	Sketch	Task <A10712AD-C71D-4342-86CB-37CB356D87D4>.<25> response ended
default	11:29:42.067336 -0500	Sketch	SUCCESS -----> {"result":{"colors":{"background_colors":[{"b":254,"closest_palette_color":"snow white","closest_palette_color_html_code":"#f2f0eb","closest_palette_color_parent":"white","closest_palette_distance":3.78965711593628,"g":254,"html_code":"#fefefe","percent":100,"r":254}],"color_percent_threshold":1.75,"color_variance":6,"foreground_colors":[{"b":248,"closest_palette_color":"snow white","closest_palette_color_html_code":"#f2f0eb","closest_palette_color_parent":"white","closest_palette_distance":3.71453523635864,"g":247,"html_code":"#faf7f8","percent":25.6344432830811,"r":250},{"b":197,"closest_palette_color":"light grey","closest_palette_color_html_code":"#BCB8B8","closest_palette_color_parent":"grey","closest_palette_distance":5.73487520217896,"g":186,"html_code":"#c1bac5","percent":9.99706649780273,"r":193},{"b":216,"closest_palette_color":"light pink","closest_palette_color_html_code":"#E6C1BE","closest_palette_color_parent":"red","closest_palette_distance":5.66262102127075,"g":210,"htm<…>
default	11:29:48.751943 -0500	Sketch	TIC Enabling TLS [36:0x604000379800]
default	11:29:48.752008 -0500	Sketch	TIC TCP Conn Start [36:0x604000379800]
default	11:29:48.752172 -0500	Sketch	Task <6C65473B-1938-4A56-AFE8-9DE035F25D20>.<10> setting up Connection 36
default	11:29:48.752209 -0500	Sketch	[36 <private> <private>] start
default	11:29:48.786808 -0500	Sketch	TIC TLS Event [36:0x604000379800]: 1, Pending(0)
default	11:29:48.810584 -0500	Sketch	TIC TLS Event [36:0x604000379800]: 2, Pending(0)
default	11:29:48.811359 -0500	Sketch	TIC TLS Event [36:0x604000379800]: 11, Pending(0)
default	11:29:48.811894 -0500	Sketch	TIC TLS Event [36:0x604000379800]: 12, Pending(0)
default	11:29:48.811955 -0500	Sketch	TIC TLS Event [36:0x604000379800]: 14, Pending(0)
default	11:29:48.823249 -0500	Sketch	System Trust Evaluation yielded status(0)
default	11:29:48.832833 -0500	Sketch	TIC TLS Trust Result [36:0x604000379800]: 0
default	11:29:48.845104 -0500	Sketch	TIC TLS Event [36:0x604000379800]: 20, Pending(0)
default	11:29:48.845178 -0500	Sketch	TIC TCP Conn Connected [36:0x604000379800]: Err(16)
default	11:29:48.845650 -0500	Sketch	TIC TCP Conn Event [36:0x604000379800]: 1
default	11:29:48.845722 -0500	Sketch	TIC TCP Conn Event [36:0x604000379800]: 8
default	11:29:48.845795 -0500	Sketch	TIC TLS Handshake Complete [36:0x604000379800]
default	11:29:48.846409 -0500	Sketch	Task <6C65473B-1938-4A56-AFE8-9DE035F25D20>.<10> now using Connection 36
default	11:29:48.846849 -0500	Sketch	Task <6C65473B-1938-4A56-AFE8-9DE035F25D20>.<10> sent request, body S
default	11:29:48.926981 -0500	Sketch	Task <6C65473B-1938-4A56-AFE8-9DE035F25D20>.<10> received response, status 200 content K
default	11:29:48.927324 -0500	Sketch	Task <6C65473B-1938-4A56-AFE8-9DE035F25D20>.<10> response ended
default	11:30:19.825553 -0500	Sketch	TIC TCP Conn Cancel [36:0x604000379800]
default	11:30:19.826345 -0500	Sketch	[36 <private> stream, pid: 65172, url: https://gate.hockeyapp.net/v2/track, tls] cancelled
	[36.1 073A4178-C283-4F5D-8262-E5D5448F2026 <private>.63188<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns
	Duration: 31.073s, DNS @0.000s took 0.021s, TCP @0.023s took 0.010s, TLS took 0.059s
	bytes in/out: 7442/1347, packets in/out: 7/4, rtt: 0.011s, retransmitted packets: 0, out-of-order packets: 0

**Comment by iarthstar** [comment]
SUCCESS -----> {"result":{"colors":{"background_colors":[{"b":254,"closest_palette_color":"snow white","closest_palette_color_html_code":"#f2f0eb","closest_palette_color_parent":"white","closest_palette_distance":3.78965711593628,"g":254,"html_code":"#fefefe","percent":100,"r":254}],"color_percent_threshold":1.75,"color_variance":6,"foreground_colors":[{"b":248,"closest_palette_color":"snow white","closest_palette_color_html_code":"#f2f0eb","closest_palette_color_parent":"white","closest_palette_distance":3.71453523635864,"g":247,"html_code":"#faf7f8","percent":25.6344432830811,"r":250},{"b":197,"closest_palette_color":"light grey","closest_palette_color_html_code":"#BCB8B8","closest_palette_color_parent":"grey","closest_palette_distance":5.73487520217896,"g":186,"html_code":"#c1bac5","percent":9.99706649780273,"r":193},{"b":216,"closest_palette_color":"light pink","closest_palette_color_html_code":"#E6C1BE","closest_palette_color_parent":"red","closest_palette_distance":5.66262102127075,"g":210,"htm<…>

**Comment by iarthstar** [comment]
I guess there was a problem with generating color shapes, I need to debug the problem. I'll work on it.

**Comment by iarthstar** [comment]
I just tested on Sketch 59, it works...

I'm guessing its because of your Sketch version 55.3, if its not an issue to update, please update your sketch and try again...
